### ISSUE TITLE
The close button in GUIs do not respond.

### ISSUE THREAD

**Issue by railworks2** [Spearritt/Soro-s-Island#1]
https://gyazo.com/3e5572e76599bcdd1a158a83bf4a83ed

Shop and teleport.

**Comment by Mazin40** [comment]
Oh here.

**Comment by Mazin40** [comment]
https://gyazo.com/1382ba983ece281da357ae17d5b9a5c4
The X button does not work and when it does this loads up.
https://gyazo.com/69f100c07681af99b0a66e0a46356b3a
Please fix! Also the drinks need to be fixed.

**Comment by Mazin40** [comment]
Also why is this repeating loading??
https://gyazo.com/6c0c60ee2ecd356533a9ef11534e5ff9
